### ISSUE TITLE
Not works with PUSH. Works only on pull_request

### ISSUE THREAD

**Issue by Rustam-Mavlyanov** [tinovyatkin/action-php-codesniffer#111]
add to .github/code_standard.yml following and push code to master branch

```
name: Coding Standards

on:
  push:
    branches:
      - "master"
    paths:
      - "**.php"
      - "**.phtml"
...
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
```

Error: 

TypeError: **Cannot read property 'base' of undefined**
    at Object.getChangedFiles **(/home/runner/work/_actions/tinovyatkin/action-php-codesniffer/v1/dist/index.js:27705:37)**
    at run (/home/runner/work/_actions/tinovyatkin/action-php-codesniffer/v1/dist/index.js:3752:48)
    at Object.198 (/home/runner/work/_actions/tinovyatkin/action-php-codesniffer/v1/dist/index.js:3777:1)
    at __webpack_require__ (/home/runner/work/_actions/tinovyatkin/action-php-codesniffer/v1/dist/index.js:22:30)
