### ISSUE TITLE
Not respecting standards file

### ISSUE THREAD

**Issue by lode** [tinovyatkin/action-php-codesniffer#40]
I have an action setup exactly as in the readme (https://github.com/tinovyatkin/action-php-codesniffer#usage), and have a `phpcs.xml` in the root of the repository which looks alike this:

```
<?xml version="1.0"?>
<ruleset>
	<arg name="colors"/>
	<file>.</file>
	<exclude-pattern>./vendor/*</exclude-pattern>
	<rule ref="Generic.Arrays.DisallowLongArraySyntax"/>
	<rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar"/>
	<rule ref="PSR2.Files.EndFileNewline"/>
</ruleset>
```

I'm including a few specific rules and no generic standard. However, I get annotations referring to `Generic.Files.LineLength.TooLong` and `PEAR.WhiteSpace.ScopeIndent.Incorrect` and others which I didn't include.

It seems thus as if my standards file is not respected/recognized and a default standard is used. Does anyone know what's going on?

**Comment by tinovyatkin** [comment]
Did you point to the file directly viat `standard` parameter? https://github.com/tinovyatkin/action-php-codesniffer/blob/4a0895ce7a8d6d6a62efdfb7d2d32d84fe8d0b7b/action.yml#L17

Can you copy your workflow file here?

**Comment by lode** [comment]
Yes, I have:

```yml
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
```

It is an exact copy of the readme.
